### ISSUE TITLE
grep -P not available on macOS

### ISSUE THREAD

**Issue by basilfx** [kaspar030/git-cache#4]
I noticed that I get errors when using `git-cache` during compilation of a RIOT-OS application. Not a big issue, and can be worked-around easily.

```shell
basilfx:pkg_u8g2/ (feature/knx✗) $ BOARD=basilfx-taster make -j16
Building application "tests_pkg_u8g2" for "basilfx-taster" with MCU "efm32".

git-cache: cloning from cache. tag=commit06b00b68333ea05db1c78fe6626dcfe005a80cb6-12552
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
```

It turns out that `grep -P` does [not](https://stackoverflow.com/questions/16658333/grep-p-no-longer-works-how-can-i-rewrite-my-searches) work on macOS. This option is used [here](https://github.com/kaspar030/git-cache/blob/master/git-cache#L197) and [here](https://github.com/kaspar030/git-cache/blob/master/git-cache#L225).

My work-around is to `brew install grep`, and put that version on my `PATH`, but maybe there is a better solution.

**Comment by kaspar030** [comment]
Thanks, I'll look into it!
